name: Crawler-Day

on:
  schedule:
    - cron : '57 23 * * 0-4'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: day

      - name: Run
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REQUEST_HOST: ${{ secrets.REQUEST_HOST }}
        run: ./gradlew run
